auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Liye's Blog”
title: Liye's blog
description: Everything about Liye.
url: 
feed: /atom.xml
author_info: <a href="http://www.dongliye.cn/">Liye</a>
